# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.cache/wt [current_project]
set_property parent.project_path C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Berke/Desktop/lab05_sevSeg/7SEG.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.srcs/sources_1/new/TranTran.vhd
  C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.srcs/sources_1/new/divider.vhd
  C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.srcs/sources_1/new/switchTran.vhd
  C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.srcs/sources_1/new/anode.vhd
  C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.srcs/sources_1/new/segSeven.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/Berke/Desktop/lab05_sevSeg/7SEG.srcs/constrs_1/new/const.xdc]


synth_design -top segSeven -part xc7a35tcpg236-1


write_checkpoint -force -noxdef segSeven.dcp

catch { report_utilization -file segSeven_utilization_synth.rpt -pb segSeven_utilization_synth.pb }
